services:
  - type: web
    runtime: node
    name: sbe-api
    plan: starter
    branch: main

    buildCommand: |
      echo "🔧 Build: install everything then build project"
      npm install --omit=dev=false
      npm run build

      echo "🧹 Clear file/dev, giữ dist/, prisma/, swagger-docs.json"
      node render-clean.mjs

      echo "📦 Re-install runtime dependencies"
      npm install express swagger-ui-express swagger-jsdoc @prisma/client

    startCommand: npm start
